// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABvGY9J_ndn9oL4De5C6pOt8_PbwNo2yw',
    appId: '1:563927563127:web:365a7fe9bdac322926bf72',
    messagingSenderId: '563927563127',
    projectId: 'flutter-learn-98c15',
    authDomain: 'flutter-learn-98c15.firebaseapp.com',
    storageBucket: 'flutter-learn-98c15.firebasestorage.app',
    measurementId: 'G-3GEKKZ5575',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHtoqLJyqFtKLU1IBMMsbfJY0NZul2PtM',
    appId: '1:563927563127:android:65b514ce30b20c3c26bf72',
    messagingSenderId: '563927563127',
    projectId: 'flutter-learn-98c15',
    storageBucket: 'flutter-learn-98c15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKUqCz_D-3HdSA4ExNUz6eq61nd6sgh2I',
    appId: '1:563927563127:ios:04024d4d8b92a61326bf72',
    messagingSenderId: '563927563127',
    projectId: 'flutter-learn-98c15',
    storageBucket: 'flutter-learn-98c15.firebasestorage.app',
    iosBundleId: 'com.example.notification',
  );
}
